/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoIdRouteImport } from './routes/catalogo.$id'

const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoIdRoute = CatalogoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CatalogoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/catalogo/$id': typeof CatalogoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/catalogo/$id': typeof CatalogoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/catalogo/$id': typeof CatalogoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/contacto'
    | '/login'
    | '/nosotros'
    | '/catalogo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/contacto'
    | '/login'
    | '/nosotros'
    | '/catalogo/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/contacto'
    | '/login'
    | '/nosotros'
    | '/catalogo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogoRoute: typeof CatalogoRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  LoginRoute: typeof LoginRoute
  NosotrosRoute: typeof NosotrosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$id': {
      id: '/catalogo/$id'
      path: '/$id'
      fullPath: '/catalogo/$id'
      preLoaderRoute: typeof CatalogoIdRouteImport
      parentRoute: typeof CatalogoRoute
    }
  }
}

interface CatalogoRouteChildren {
  CatalogoIdRoute: typeof CatalogoIdRoute
}

const CatalogoRouteChildren: CatalogoRouteChildren = {
  CatalogoIdRoute: CatalogoIdRoute,
}

const CatalogoRouteWithChildren = CatalogoRoute._addFileChildren(
  CatalogoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogoRoute: CatalogoRouteWithChildren,
  ContactoRoute: ContactoRoute,
  LoginRoute: LoginRoute,
  NosotrosRoute: NosotrosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
